#!/usr/bin/env node
'use strict';

// Bundles prototype/data/*.json (the single source of truth for every game number)
// into prototype/data/game-data.js, a plain script that defines `GAME_DATA`.
// The bundle exists only so the game also runs from a double-clicked file://
// page (browsers block fetch() of JSON there). Unreal imports the JSON directly.
//
//   node prototype/tools/build-data.cjs          # rebuild the bundle
//   node prototype/tools/build-data.cjs --check  # fail if the bundle is stale (used by tests)

const fs = require('node:fs');
const path = require('node:path');

const DATA_DIR = path.join(__dirname, '..', 'data');
const OUT = path.join(DATA_DIR, 'game-data.js');

function bundle() {
  const files = fs.readdirSync(DATA_DIR).filter((name) => name.endsWith('.json')).sort();
  const data = {};
  for (const file of files) {
    const key = path.basename(file, '.json');
    data[key] = JSON.parse(fs.readFileSync(path.join(DATA_DIR, file), 'utf8'));
  }
  return '// GENERATED by prototype/tools/build-data.cjs from prototype/data/*.json — do not edit.\n'
    + `// Sources: ${files.join(', ')}\n`
    + `const GAME_DATA = ${JSON.stringify(data, null, 2)};\n`
    + "if (typeof module !== 'undefined') module.exports = GAME_DATA;\n";
}

const text = bundle();
if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== text) {
    console.error('prototype/data/game-data.js is stale — run: node prototype/tools/build-data.cjs');
    process.exit(1);
  }
  console.log('Game data bundle is up to date.');
} else {
  fs.writeFileSync(OUT, text);
  console.log(`Wrote ${path.relative(process.cwd(), OUT)} (${text.length} bytes)`);
}
