#!/usr/bin/env node
'use strict';

// Generates docs/GAME_DATA_TABLES.md from prototype/data/*.json, evaluated through the
// real simulation (prices per level, per-wave difficulty, recommendations), so the
// reference tables can never drift from the code.
//
//   node prototype/tools/gen-rules.cjs           # rewrite the tables
//   node prototype/tools/gen-rules.cjs --check   # fail if the file is stale (used by tests)

const fs = require('node:fs');
const path = require('node:path');
const { loadGame } = require('./load-game.cjs');

const OUT = path.join(__dirname, '..', '..', 'docs', 'GAME_DATA_TABLES.md');
const { run } = loadGame({ simOnly: true });
const D = JSON.parse(run('JSON.stringify(GAME_DATA)'));
const n = (value, digits = 2) => (Number.isInteger(value) ? String(value) : Number(value).toFixed(digits));
const table = (head, rows) => [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');

const out = [];
out.push('# Game data tables (generated)');
out.push('');
out.push('Generated by `node prototype/tools/gen-rules.cjs` from `prototype/data/*.json`, evaluated through `src/sim`.');
out.push('Do not edit by hand. Formulas are explained in `docs/GAME_RULES.md`.');

out.push('\n## Enemies (base stats, before wave multipliers)\n');
out.push(table(['id', 'name', 'hp', 'damage', 'attack every s', 'speed ×', 'gold', 'steals', 'traits', 'boss'],
  Object.entries(D.enemies.types).map(([id, e]) => [id, e.name, e.hp, e.damage, e.attackRate, e.speed, e.reward, e.loot,
    [...(e.traits || []).filter((t) => !(t === 'armor' && e.armor) && !(t === 'ranged' && e.range)), e.armor ? `armor ${e.armor}` : '', e.range ? `ranged ${e.range}` : ''].filter(Boolean).join(', ') || '—', e.isBoss ? 'yes' : ''])));
out.push('\nTraits: ' + Object.entries(D.enemies.traits).map(([k, v]) => `**${k}** — ${v.description}`).join('; ') + '.');

out.push('\n## Waves\n');
const waves = [];
for (let w = 1; w <= D.waves.finalWave; w += 1) {
  const diff = JSON.parse(run(`JSON.stringify(calculateWaveDifficulty(${w}, expectedProgress(${w})))`));
  const exp = JSON.parse(run(`JSON.stringify(expectedProgress(${w}))`));
  const boss = run(`isBossWave(${w})`) ? (w % 10 === 0 ? 'mega' : 'mini') : '';
  waves.push([w, D.waves.plans[w].join(', '), run(`maxConcurrent(${w})`), n(diff.hp), n(diff.damage), exp.guardLevel, exp.spikesLevel,
    exp.archerLevel || '—', exp.heroLevel, run(`requiredTown(${w})`), boss]);
}
out.push(table(['wave', 'roster (spawn order)', 'max at once', 'enemy HP ×', 'enemy dmg ×', 'exp. frontline', 'exp. spikes', 'exp. tower', 'exp. hero lv', 'needs village', 'boss'], waves));

out.push('\n## Prices by level (cost of buying the next level)\n');
const kinds = [['frontline (food)', 'guard'], ['farm (gold)', 'farm'], ['spikes (gold)', 'spikes'], ['archer (gold)', 'archer'], ['catapult (gold)', 'catapult']];
const levels = [1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 20, 25, 30];
out.push(table(['item', ...levels.map((l) => `lv ${l}→${l + 1}`)], kinds.map(([label, key]) => [label,
  ...levels.map((l) => run(`priceAt(ECONOMY.${key}Base, ECONOMY.${key}Growth, ${l})`))])));
out.push(`\nCaps per village level V: frontline & farm = 5·V, spikes = 2·V (after wave ${D.economy.spikes.unlockAfterWave}), archer & catapult = 5·(V−1).`);

out.push('\n## Heroes and spells\n');
out.push(table(['id', 'name', 'slot', 'damage ×', 'damage taken ×', 'spell', 'cooldown s', 'effect'],
  Object.entries(D.heroes.heroes).map(([id, h]) => [id, h.name, h.role, h.damageMult, h.guardTaken ?? '—', h.spell ? h.spell.name : '— (machine)', h.spell ? h.spell.cooldown : '—', h.spell ? h.spell.hint : 'never tires'])));
out.push(`\nSlots unlock at village: ${Object.entries(D.heroes.slotUnlockVillage).map(([k, v]) => `${k} ${v}`).join(', ')}. Hoplite joins after wave ${D.heroes.hopliteUnlockWave}.`);
out.push(`Fatigue: −${D.heroes.fatigue.penaltyPerWave * 100}% damage per consecutive wave after the first (max ${D.heroes.fatigue.max}), rested +${D.heroes.fatigue.restedBonus * 100}% and spell ready.`);

out.push('\n## Boss rewards, village and systems\n');
out.push(table(['village', 'needs boss of wave', 'cost', 'slots / unlocks', 'offline cap h'], Array.from({ length: D.progression.village.max }, (_, i) => {
  const v = i + 1;
  const slot = Object.entries(D.heroes.slotUnlockVillage).filter(([, lv]) => lv === v).map(([k]) => `${k} slot`).join(', ');
  run(`state.townLevel = ${v}`);
  return [v, v === 1 ? '—' : 5 * (v - 1), v === 1 ? '—' : `${D.progression.village.costTrophies} trophy`, slot || '—', run('offlineCapHours()')];
})));
out.push(`\nMini-boss every ${D.progression.bosses.miniEvery} waves: ${D.progression.bosses.mini.trophies} trophy. Mega-boss every ${D.progression.bosses.megaEvery}: ${D.progression.bosses.mega.trophies} trophies + ${D.progression.bosses.mega.eagles} eagle.`);
out.push('\n' + table(['system', 'eagle after wave', 'what it does'], D.progression.systems.map((s) => [s.name, s.wave, s.text])));

out.push('\n## Armory\n');
out.push(table(['slot', 'bonus', ...D.systems.armory.rarity], Object.entries(D.systems.armory.slots).map(([k, s]) => [k, s.label, ...s.values.map((v, i) => `${s.names[i]} ${Math.round(v * 100)}%`)])));
out.push(`\nDrops cycle weapon → armor → charm. Mini-boss ${D.systems.armory.miniBossItems} item, mega-boss ${D.systems.armory.megaBossItems}; every ${D.systems.armory.eliteDropEvery}th elite (${D.systems.armory.eliteTypes.join(', ')}) kill drops one.`);

out.push('\n## Barracks and Temple\n');
out.push(`Training: cost = ${D.systems.barracks.base} × ${D.systems.barracks.growth}^(level−1) food; +${D.systems.barracks.damage * 100}% damage and +${D.systems.barracks.toughness * 100}% toughness per level.`);
out.push('\n' + table(['god', 'pays with', 'base cost', 'growth', 'per level', 'cap'], Object.entries(D.systems.gods).map(([k, g]) => [g.name, g.resource === 'coins' ? 'gold' : 'food', g.base, g.growth, `${g.per * 100}% ${g.text}`, g.cap ? `${g.cap * 100}%` : '—'])));

out.push('\n## Offline income\n');
out.push(`Efficiency ${D.offline.efficiency * 100}% of live rates, from ${D.offline.minSeconds} s; gold 1 per ${D.offline.goldEvery} s; food = farm level per ${D.economy.farm.tickSeconds} s.`);
out.push('\n' + table(['offline', 'farm 3', 'farm 5', 'farm 10'], [600, 3600, 7200, 14400, 28800].map((s) => {
  run('state.townLevel = 5');
  return [`${s / 3600} h`, ...[3, 5, 10].map((f) => { const r = JSON.parse(run(`JSON.stringify(offlineIncome(${s}, ${f}))`)); return `${r.food} food, ${r.gold} gold`; })];
})));
out.push('');

const text = out.join('\n');
if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== text) { console.error('docs/GAME_DATA_TABLES.md is stale — run: node prototype/tools/gen-rules.cjs'); process.exit(1); }
  console.log('Data tables are up to date.');
} else {
  fs.writeFileSync(OUT, text);
  console.log(`Wrote ${path.relative(process.cwd(), OUT)}`);
}
